config/routes.rb
Rails.application.routes.draw do
  root to: 'rooms#show'
  get "/sessions/" => 'rooms#show'
  get "/about/" => 'application#show'

  mount ActionCable.server => '/cable'

  resources :users, only: [:edit, :update, :show] do
    get "/change_password" => "users#change_password"
  end

  resources :sessions, only: [:new, :create, :destroy] do
    delete :destroy, on: :collection
    # get :forgot_password, on: :collection
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  after_create_commit { BroadcastMessageJob.perform_later self  }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :messages, dependent: :destroy

  validates :username, uniqueness: true
  validates :password, presence: true, length: {minimum: 6}, on: :update

  # def online?
  #   !Redis.new.get("user_#{self.id}_online").nil?
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!

  def sign_in(user)
    cookies.signed[:user_id] = user.id
  end

  def user_signed_in?
    cookies.signed[:user_id].present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find(cookies.signed[:user_id]) if user_signed_in?
  end
  helper_method :current_user

  def authenticate_user
    redirect_to new_session_path, notice: "Please sign in." unless user_signed_in?
  end

  def show
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :authenticate_user

  def show
    @messages = Message.order(created_at: :DESC)
  end

  def create
    @message = Message.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
      user = User.find_by_username params[:username]
      if user && user.authenticate(params[:password])
        sign_in(user)
        redirect_to root_path, notice: "Sign in successful!"
      else
        flash[:alert] = "Invalid credentials! Please try again."
        render :new
      end
    end

    def destroy
      cookies.signed[:user_id] = nil
      redirect_to root_path, notice: "You've been logged out!"
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :change_password, :check_password]

    def show
    end

    def edit
    end

    def update
      if check_password
        if @user.update user_params
          redirect_to user_path(@user), notice: "Profile updated successfully."
        else
          flash[:notice] = "Profile not updated."
          @changing_password ? (render :change_password) : (render :edit)
        end
      else
        flash[:alert] = "Wrong credentials!"
        @changing_password ? (render :change_password) : (render :edit)
      end
    end

    def change_password
    end

    private

    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation)
    end

    def find_user
      @user = User.find current_user.id
    end

    def check_password
      authentic_password = @user.authenticate(params[:user]["current_password"])
      different_password = params[:user]["current_password"] != params[:user]["password"]
      @changing_password = params[:user]["password"]
      @changing_password ? (authentic_password && different_password) : authentic_password
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.username
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.username)}?s=#{opts.delete(:size) { 40 }}", opts
  end

  def emojify(content)
  h(content).to_str.gsub(/:([\w+-]+):/) do |match|
    if emoji = Emoji.find_by_alias($1)
      %(<img alt="#$1" src="#{image_path("emoji/#{emoji.image_filename}")}" style="vertical-align:middle" width="20" height="20" />)
    else
      match
    end
  end.html_safe if content.present?
end

  # def online_status(user)
  # content_tag :span, user.name,
  #             class: "user-#{user.id} online_status #{'online' if user.online?}"
  # end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/show.html.erb
<div class="jumbotron">
  <h1>Welcome!</h1>
  <h2>1111 Beach is the <i>residents-only</i> community hub for dwellers of 1111 Beach Avenue.</h2>
  <p>How many of your neighbors do you know? If you know any, that's already good, but hopefully this app empowers you to get to know more of them, and enhance the quality of life!</p>
</div>

app/views/layouts/_flash_errors.html.erb
<% if flash.notice %>
  <div class="alert alert-danger">
      <% flash.notice.each do |type, messages|%>
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span><%messages.each do |msg|%>
          <%=type%> <%=msg%>
        <%end%>
      <%end%>
  </div>
<%end%>

app/views/layouts/_navbar.html.erb
  <nav class="navbar navbar-default">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path do %>
         <%= image_tag "palmtreeSM.png", alt: "Palm Tree", class: "palmtree" %>
      <% end %>
      <%= link_to root_path do %>
         <%= image_tag "1111beachSM.png", alt: "1111 Beach", class: "beach1111" %>
      <% end %>
      <%# link_to root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= render partial: 'layouts/navbar_links' %>
    </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/_navbar_links.html.erb
<% if user_signed_in? %>
  <ul class="nav navbar-nav navbar-right">
    <li>
      <%# link_to "My Profile", user_path(current_user) %>
    </li>
    <li>
      <% if current_user.username != "1903" %>
        <%= link_to "Welcome #{current_user.username}!", user_path(current_user) %>
      <% elsif %>
        <%= link_to "Welcome admin!", user_path(current_user) %>
      <% end %>
    </li>
    <li>
      <%= link_to "Log Out", sessions_path, method: :delete, data: {confirm: "Are you sure you want to log out?"} %>
    </li>
  </ul>
<% end %>
<ul class="nav navbar-right navbar-nav">
  <li>
    <%= link_to "About", about_path  %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html5>
<html>
  <head>
    <title>1111 Beach</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="http://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link rel="icon" href="https://d30y9cdsu7xlg0.cloudfront.net/png/10397-200.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.2.0/gh-fork-ribbon.min.css" />

  </head>

  <body>

    <div class="container">
<div class="hidden" id="snow"></div>
<a class="github-fork-ribbon right-bottom fixed" href="#" title="1111 Make a Wish" id="toggle-snow"></a>



      <%= render partial: 'layouts/navbar' %>

        <% if notice || alert %>
        <div
        class="alert alert-<%= notice ? 'success' : 'danger'%> alert-dismissable"
        role="alert">
        <%= notice || alert %>
        <span class="close" aria-hidden="true">&times;</span>
      </div>
    <% end %>
    </div>

    <div class="container">
      <%= yield %>
    </div>
</body>
</html>

app/views/messages/_message.html.erb
<div class="message" id="messages">

<p><%# message.created_at %><strong><%#message.user.username%></strong> <%#message.content%></p>

<div class="card">
  <div class="card-block">
    <div class="row noMargin">
      <div class="col-md-1">
        <% if message.user.username == "1903" %>
          <%= image_tag("19032.png", size: "40x40") %>
        <% else %>
          <%= gravatar_for message.user %>
        <% end %>
      </div>
      <div class="col-md-11">
        <p class="card-text">
          <span class="text-muted"><strong><%= message.user.username %></strong> at <%= message.created_at %> says</span><br>
          <%= Emoji.replace_unicode_moji_with_images(message.content) %>
        </p>
      </div>
    </div>

  </div>
</div>
</div>

app/views/rooms/show.html.erb
  <div class="col-md-3 noPaddingLeft" >
    <div class="col-md-12" id="welcome-text">
      <%if user_signed_in?%>
      <!-- <div class="container-fluid"> -->
      <h3>Hiya <%= current_user.username%>!  <img src="http://www.emoji.co.uk/files/google-emojis/smileys-people-android/7283-waving-hand-sign.png" style="max-width: 20px; margin-top: -5px" alt="" /></h3>
      <p>1903 here. I'm demoing this project on December 15th between 6-9pm at my school and woud love to chat with you at that time!</p>
      <p style="display: inline">
        Mark your calendar
      </p> <a target="_blank" href="https://calendar.google.com/calendar/event?action=TEMPLATE&amp;tmeid=aWdycnIwcGVqN291ZTZraXJkNnBsY3EwYnMgYjRidG42bWQwdTBpbWxkazczZWI4a3NiYWdAZw&amp;tmsrc=b4btn6md0u0imldk73eb8ksbag%40group.calendar.google.com"><img border="0" src="https://www.google.com/calendar/images/ext/gc_button1_en.gif"></a>
      <%end%>
      <br>
      <br>
    </div>

    <div class="col-md-12" style="margin-top: 5px; background-color: #ccc; border-radius: 5px; display: flex" id="connected-users">
      <!-- User List is here -->
      <p style="margin: 5 0 5"><%= image_tag("http://1.bp.blogspot.com/-Kxj8PwiqsvE/TaEZGnOKfKI/AAAAAAAAACg/Umk-kiGnJIQ/s1600/GreenDot.png", width: "14") %>
      <%= ActionCable.server.connections.length %> neighbours are online.
    </p>
    </div>

    <div class="col-md-12" style="margin-top: 5px; background-color: white; border-radius: 5px; display: flex">
      <a class="twitter-timeline"  href="https://twitter.com/hashtag/vancouver" data-widget-id="809533847998119936">#vancouver Tweets</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

    </div>
  </div>
<!-- </div> -->
<%# content_for :title, 'admin | Action Cable Chat' %>
<div class="col-md-9 noPaddingRight">


  <label for="comment" style="padding-top:5px">Message:</label>



  <div class="newMessage" id="newMessage">
    <textarea class="form-control" rows="3" placeholder="Enter your message here." id="message_input"></textarea>
    <input type="button" value="Send" id="new_message" class="btn btn-primary btn-lg">

  </div>


  <div class="message-container rounded strech" id="messages">
    <%= render @messages %>
  </div>
</div>

app/views/users/_users.html.erb
<li>
  <%= message.user.username %>
</li>

app/views/users/change_password.html.erb
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
  <h1>Change Password</h1>

  <%= form_for @user do |f| %>
    <%= content_tag(:div, class: "form-group") do %>
      <%= f.label :current_password %>
      <%= f.password_field :current_password, class: "form-control" %>
    <% end %>
    <%= content_tag(:div, class: "form-group") do %>
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
    <% end %>
    <%= content_tag(:div, class: "form-group") do %>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    <% end %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>
</div>
</div>
</div>
</div>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <% if user_signed_in?%>
    <%= f.input :current_password %>
  <% else %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
  <% end %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>


<%= link_to "Change Password", user_change_password_path(@user) %>

app/views/users/show.html.erb
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
              <div class="form-group">
              <h1>Your Profile</h1>
              <p>Username: <%= @user.username %></p>
              <p>Password: ******** </p>
              </div>

                <%= link_to "Update Password", user_change_password_path(@user), class: "btn btn-primary" %>

</div>
</div>
</div>
</div>